services:
  docs:
    image: desafio_prozis_local_docs
    container_name: desafio_prozis_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./desafio_prozis:/app/desafio_prozis:z
    ports:
      - '9000:9000'
    command: /start-docs
