volumes:
  desafio_prozis_local_postgres_data: {}
  desafio_prozis_local_postgres_data_backups: {}
  desafio_prozis_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: desafio_prozis_local_django
    container_name: desafio_prozis_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8001:8001'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: desafio_prozis_production_postgres
    container_name: desafio_prozis_local_postgres
    volumes:
      - desafio_prozis_local_postgres_data:/var/lib/postgresql/data
      - desafio_prozis_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: desafio_prozis_local_redis

    volumes:
      - desafio_prozis_local_redis_data:/data

  celeryworker:
    <<: *django
    image: desafio_prozis_local_celeryworker
    container_name: desafio_prozis_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: desafio_prozis_local_celerybeat
    container_name: desafio_prozis_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: desafio_prozis_local_flower
    container_name: desafio_prozis_local_flower
    ports:
      - '5556:5556'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: desafio_prozis_local_node
    container_name: desafio_prozis_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3003:3003'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3002:3002'
