# Generated by Django 5.1.8 on 2025-04-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem da instrução no prompt')),
                ('text', models.TextField(help_text='Texto da instrução')),
            ],
            options={
                'verbose_name': 'Prompt Instruction',
                'verbose_name_plural': 'Prompt Instructions',
                'db_table': 'llm_prompt_instructions',
                'ordering': ('order',),
            },
        ),
    ]
