# Generated by Django 5.1.8 on 2025-04-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userintention_options_and_more'),
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Instruction text')),
                ('expected_label', models.ForeignKey(help_text='Label Expected', on_delete=django.db.models.deletion.CASCADE, related_name='expected_unit_tests', to='core.userintention')),
                ('predicted_label', models.ForeignKey(blank=True, help_text='Predicted label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_unit_tests', to='core.userintention')),
            ],
            options={
                'verbose_name': 'Unit Test',
                'verbose_name_plural': 'Unit Tests',
                'db_table': 'unit_test',
            },
        ),
    ]
