# Generated by Django 5.1.8 on 2025-04-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userintention_options_and_more'),
        ('ml_models', '0002_unittest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unittest',
            unique_together={('text', 'expected_label')},
        ),
    ]
