# Generated by Django 5.1.8 on 2025-04-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0003_alter_unittest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittest',
            name='custom_test',
            field=models.BooleanField(default=False, help_text='whether it is a test created by prozis or not'),
        ),
    ]
