# Generated by Django 5.1.8 on 2025-05-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_unittest_custom_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptInstruction',
        ),
    ]
