# Generated by Django 5.1.8 on 2025-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0005_delete_promptinstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_action', models.CharField(blank=True, help_text='What the process is currently doing.', max_length=200)),
                ('last_action', models.CharField(blank=True, help_text='The last action performed by the process.', max_length=200)),
                ('celery_running', models.BooleanField(default=False)),
                ('celery_task', models.CharField(default='', editable=False, help_text='ID generated by celery while is running', max_length=100, verbose_name='Celery Task ID')),
                ('celery_status', models.CharField(default='NO INFO', editable=False, help_text='Last status reported from celery', max_length=100, verbose_name='Celery Status')),
                ('started', models.DateTimeField(auto_now_add=True, null=True, verbose_name='start')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='end')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
