# Generated by Django 5.1.8 on 2025-04-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userintention',
            options={'verbose_name': 'User Intention', 'verbose_name_plural': 'User Intentions'},
        ),
        migrations.AlterModelTable(
            name='userintention',
            table='user_intention',
        ),
    ]
