# Generated by Django 5.1.8 on 2025-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userintention_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintention',
            name='ml_text',
            field=models.CharField(blank=True, help_text='Texto adaptado para uso no modelo', max_length=150),
        ),
    ]
