# Generated by Django 5.1.8 on 2025-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userintention_ml_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintention',
            name='ml_text',
            field=models.CharField(help_text='Texto adaptado para uso no modelo', max_length=150),
        ),
    ]
